openapi: 3.0.3
info:
    title: Key Stone
    description: Key Stone is a platform for managing your keys
    version: v0.0.1
servers:
    - url: http://localhost:80
      description: Default server for key-stone
paths:
    /key-stone/auth:
        post:
            tags:
                - token
            summary: issue token
            operationId: token#issue
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/IssueInput'
                        example:
                            password: Illo et rerum quia odit voluptas.
                            username: Esse sapiente temporibus vel.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TokenDetail'
                            example:
                                access_token: Saepe quo dolores dolorum.
                                expires_in: 8813850995321923442
                                refresh_token: Est sed alias qui mollitia ab.
                                token_type: Delectus fugit et quia illum facere distinctio.
                "401":
                    description: 'Unauthorized: Unauthorized'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /key-stone/auth/refresh:
        post:
            tags:
                - token
            summary: refresh token
            operationId: token#refresh
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RefreshInput'
                        example:
                            access_token: Laboriosam exercitationem.
                            refresh_token: Voluptatem sit culpa.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TokenDetail'
                            example:
                                access_token: Quos temporibus nobis est sunt.
                                expires_in: 6385642804668407170
                                refresh_token: Cumque suscipit quia aperiam tempore.
                                token_type: Dolore et minus cumque.
                "401":
                    description: 'Unauthorized: Unauthorized'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'InternalServerError: Internal Server Error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /key-stone/users:
        post:
            tags:
                - user
            summary: create user
            operationId: user#create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UserInput'
                        example:
                            password: Occaecati vel adipisci.
                            username: Quia architecto veritatis deleniti ea perferendis.
            responses:
                "204":
                    description: No Content response.
                "401":
                    description: 'UserAlreadyExists: User Already Exists'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'InternalServerError: Internal Server Error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /key-stone/users/me:
        delete:
            tags:
                - user
            summary: delete user
            operationId: user#delete
            responses:
                "204":
                    description: No Content response.
                "401":
                    description: 'Unauthorized: Unauthorized'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'InternalServerError: Internal Server Error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        DeleteUserPayload:
            type: object
            properties:
                Authorization:
                    type: string
                    description: The payload of the user
                    example: Rerum qui et omnis.
            example:
                Authorization: Molestiae cumque ut facere.
            required:
                - Authorization
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            description: User Already Exists
            example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        IssueInput:
            type: object
            properties:
                password:
                    type: string
                    description: The password of the user
                    example: Ea cumque et hic.
                username:
                    type: string
                    description: The username of the user
                    example: Reiciendis dolor et veniam sapiente fugiat.
            example:
                password: Dolores omnis omnis quo asperiores aliquam.
                username: Non rerum laudantium.
            required:
                - username
                - password
        RefreshInput:
            type: object
            properties:
                access_token:
                    type: string
                    description: The access token of the user
                    example: Beatae consequatur.
                refresh_token:
                    type: string
                    description: The refresh token of the user
                    example: Totam voluptate et nihil maxime consequatur qui.
            example:
                access_token: Excepturi rem ipsum earum quod commodi.
                refresh_token: Nostrum repellat placeat.
            required:
                - access_token
                - refresh_token
        TokenDetail:
            type: object
            properties:
                access_token:
                    type: string
                    description: The access token of the user
                    example: Placeat illo.
                expires_in:
                    type: integer
                    description: The expires in of the user
                    example: 3131122254858954477
                    format: int64
                refresh_token:
                    type: string
                    description: The refresh token of the user
                    example: Harum dolores quia.
                token_type:
                    type: string
                    description: The token type of the user
                    example: Reprehenderit et eveniet quasi laboriosam nobis minus.
            example:
                access_token: Dolorum ut.
                expires_in: 3927542106776064148
                refresh_token: Eius consequatur repellendus.
                token_type: Quidem quia.
            required:
                - access_token
                - token_type
                - expires_in
                - refresh_token
        UserInput:
            type: object
            properties:
                password:
                    type: string
                    description: The password of the user
                    example: Ex ut.
                username:
                    type: string
                    description: The name of the user
                    example: Reprehenderit velit aliquam minima qui harum.
            example:
                password: Nulla dolor recusandae illo.
                username: Quia mollitia consectetur enim.
            required:
                - username
                - password
tags:
    - name: user
    - name: token
