swagger: "2.0"
info:
    title: Key Stone
    description: Key Stone is a platform for managing your keys
    version: v0.0.1
host: localhost:80
basePath: /key-stone
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /auth:
        post:
            tags:
                - token
            summary: issue token
            operationId: token#issue
            parameters:
                - name: IssueRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/IssueInput'
                    required:
                        - username
                        - password
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TokenDetail'
                        required:
                            - access_token
                            - token_type
                            - expires_in
                            - refresh_token
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/TokenIssueUnauthorizedResponseBody'
            schemes:
                - http
    /auth/refresh:
        post:
            tags:
                - token
            summary: refresh token
            operationId: token#refresh
            parameters:
                - name: RefreshRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/RefreshInput'
                    required:
                        - access_token
                        - refresh_token
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TokenDetail'
                        required:
                            - access_token
                            - token_type
                            - expires_in
                            - refresh_token
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/TokenRefreshUnauthorizedResponseBody'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/TokenRefreshInternalServerErrorResponseBody'
            schemes:
                - http
    /users:
        post:
            tags:
                - user
            summary: create user
            operationId: user#create
            parameters:
                - name: CreateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserInput'
                    required:
                        - username
                        - password
            responses:
                "204":
                    description: No Content response.
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/UserCreateUserAlreadyExistsResponseBody'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/UserCreateInternalServerErrorResponseBody'
            schemes:
                - http
    /users/me:
        delete:
            tags:
                - user
            summary: delete user
            operationId: user#delete
            parameters:
                - name: Authorization
                  in: header
                  description: The authorization header
                  required: true
                  type: string
            responses:
                "204":
                    description: No Content response.
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/UserDeleteUnauthorizedResponseBody'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/UserDeleteInternalServerErrorResponseBody'
            schemes:
                - http
definitions:
    IssueInput:
        title: IssueInput
        type: object
        properties:
            password:
                type: string
                description: The password of the user
                example: Illum tempore magnam doloribus qui est alias.
            username:
                type: string
                description: The username of the user
                example: Aspernatur facere odit in molestiae quos.
        example:
            password: Sed nemo maxime eaque tempora non.
            username: Illum ducimus reprehenderit assumenda dolor rerum.
        required:
            - username
            - password
    RefreshInput:
        title: RefreshInput
        type: object
        properties:
            access_token:
                type: string
                description: The access token of the user
                example: Repellendus in sint quae consequuntur quibusdam.
            refresh_token:
                type: string
                description: The refresh token of the user
                example: Vel libero dolor.
        example:
            access_token: Tempore corporis odit aspernatur et dolorum.
            refresh_token: Et consequatur nam atque soluta quos sed.
        required:
            - access_token
            - refresh_token
    TokenDetail:
        title: TokenDetail
        type: object
        properties:
            access_token:
                type: string
                description: The access token of the user
                example: Impedit similique autem odio nihil.
            expires_in:
                type: integer
                description: The expires in of the user
                example: 2799093750981729898
                format: int64
            refresh_token:
                type: string
                description: The refresh token of the user
                example: Nihil consequatur incidunt.
            token_type:
                type: string
                description: The token type of the user
                example: Expedita soluta ex vel et.
        example:
            access_token: Tempora numquam nisi eaque.
            expires_in: 4028798900170104312
            refresh_token: Non ad adipisci accusamus.
            token_type: Explicabo ipsum distinctio consequatur consectetur blanditiis repudiandae.
        required:
            - access_token
            - token_type
            - expires_in
            - refresh_token
    TokenIssueUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Unauthorized (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TokenRefreshInternalServerErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Internal Server Error (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TokenRefreshUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Unauthorized (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserCreateInternalServerErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Internal Server Error (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserCreateUserAlreadyExistsResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: User Already Exists (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserDeleteInternalServerErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Internal Server Error (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserDeleteUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Unauthorized (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserInput:
        title: UserInput
        type: object
        properties:
            password:
                type: string
                description: The password of the user
                example: Repellat voluptatem consectetur.
            username:
                type: string
                description: The name of the user
                example: Occaecati qui in.
        example:
            password: Omnis neque quas animi ut nihil.
            username: Ad officia vel dolorem fuga.
        required:
            - username
            - password
