openapi: 3.0.3
info:
    title: Key Stone
    description: Key Stone is a platform for managing your keys
    version: v0.0.1
servers:
    - url: http://localhost:80
      description: Default server for key-stone
paths:
    /key-stone/auth:
        post:
            tags:
                - token
            summary: issue token
            operationId: token#issue
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            user:
                                password: Sapiente temporibus vel.
                                username: Dolores fuga asperiores voluptatem aspernatur eum.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TokenDetail'
                            example:
                                access_token: Illo et rerum quia odit voluptas.
                                expires_in: 211348543797255040
                                refresh_token: Fugit et.
                                token_type: Saepe quo dolores dolorum.
                "400":
                    description: 'BadRequest: Bad Request'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "401":
                    description: 'Unauthorized: Unauthorized'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /key-stone/auth/refresh:
        post:
            tags:
                - token
            summary: refresh token
            operationId: token#refresh
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RefreshRequestBody'
                        example:
                            token:
                                access_token: Sed alias qui mollitia ab delectus a.
                                refresh_token: Ducimus laboriosam exercitationem eos.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TokenDetail'
                            example:
                                access_token: Sit culpa fugiat quos temporibus nobis est.
                                expires_in: 4474053281006103846
                                refresh_token: Suscipit quia.
                                token_type: Consectetur dolore et minus cumque quia.
                "400":
                    description: 'BadRequest: Bad Request'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "401":
                    description: 'Unauthorized: Unauthorized'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /key-stone/users:
        post:
            tags:
                - user
            summary: create user
            operationId: user#create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            user:
                                password: Occaecati vel adipisci.
                                username: Quia architecto veritatis deleniti ea perferendis.
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: 'BadRequest: Bad Request'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /key-stone/users/me:
        delete:
            tags:
                - user
            summary: delete user
            operationId: user#delete
            responses:
                "204":
                    description: No Content response.
                "401":
                    description: 'Unauthorized: Unauthorized'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        CreateRequestBody:
            type: object
            properties:
                user:
                    $ref: '#/components/schemas/UserInput'
            example:
                user:
                    password: Occaecati vel adipisci.
                    username: Quia architecto veritatis deleniti ea perferendis.
            required:
                - user
        DeleteUserPayload:
            type: object
            properties:
                Authorization:
                    type: string
                    description: The payload of the user
                    example: Et consequatur nam atque soluta quos sed.
            example:
                Authorization: Reprehenderit velit aliquam minima qui harum.
            required:
                - Authorization
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            description: Bad Request
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        IssueInput:
            type: object
            properties:
                password:
                    type: string
                    description: The password of the user
                    example: Quia mollitia consectetur enim.
                username:
                    type: string
                    description: The username of the user
                    example: Ex ut.
            example:
                password: Rerum qui et omnis.
                username: Nulla dolor recusandae illo.
            required:
                - username
                - password
        RefreshInput:
            type: object
            properties:
                access_token:
                    type: string
                    description: The access token of the user
                    example: Quasi laboriosam nobis minus voluptatem ut.
                refresh_token:
                    type: string
                    description: The refresh token of the user
                    example: Dolores quia aut.
            example:
                access_token: Ut cum quidem quia dolorum esse.
                refresh_token: Consequatur repellendus ab beatae consequatur.
            required:
                - access_token
                - refresh_token
        RefreshRequestBody:
            type: object
            properties:
                token:
                    $ref: '#/components/schemas/RefreshInput'
            example:
                token:
                    access_token: Sed alias qui mollitia ab delectus a.
                    refresh_token: Ducimus laboriosam exercitationem eos.
            required:
                - token
        TokenDetail:
            type: object
            properties:
                access_token:
                    type: string
                    description: The access token of the user
                    example: Molestiae cumque ut facere.
                expires_in:
                    type: integer
                    description: The expires in of the user
                    example: 2950528847670145197
                    format: int64
                refresh_token:
                    type: string
                    description: The refresh token of the user
                    example: Cumque et hic omnis non rerum.
                token_type:
                    type: string
                    description: The token type of the user
                    example: Reiciendis dolor et veniam sapiente fugiat.
            example:
                access_token: Rerum dolores omnis.
                expires_in: 1504666541525797473
                refresh_token: Molestiae reprehenderit et.
                token_type: Quo asperiores aliquam ducimus.
            required:
                - access_token
                - token_type
                - expires_in
                - refresh_token
        UserInput:
            type: object
            properties:
                password:
                    type: string
                    description: The password of the user
                    example: Repellendus in sint quae consequuntur quibusdam.
                username:
                    type: string
                    description: The name of the user
                    example: Aut officiis ea ipsa.
            example:
                password: Tempore corporis odit aspernatur et dolorum.
                username: Vel libero dolor.
            required:
                - username
                - password
tags:
    - name: user
    - name: token
