swagger: "2.0"
info:
    title: Key Stone
    description: Key Stone is a platform for managing your keys
    version: v0.0.1
host: localhost:80
basePath: /key-stone
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /auth:
        post:
            tags:
                - token
            summary: issue token
            operationId: token#issue
            parameters:
                - name: IssueRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TokenIssueRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TokenDetail'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/TokenIssueBadRequestResponseBody'
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/TokenIssueUnauthorizedResponseBody'
            schemes:
                - http
    /auth/refresh:
        post:
            tags:
                - token
            summary: refresh token
            operationId: token#refresh
            parameters:
                - name: RefreshRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TokenRefreshRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TokenDetail'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/TokenRefreshBadRequestResponseBody'
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/TokenRefreshUnauthorizedResponseBody'
            schemes:
                - http
    /users:
        post:
            tags:
                - user
            summary: create user
            operationId: user#create
            parameters:
                - name: CreateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserCreateRequestBody'
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/UserCreateBadRequestResponseBody'
            schemes:
                - http
    /users/me:
        delete:
            tags:
                - user
            summary: delete user
            operationId: user#delete
            parameters:
                - name: Authorization
                  in: header
                  description: The authorization header
                  required: true
                  type: string
            responses:
                "204":
                    description: No Content response.
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/UserDeleteUnauthorizedResponseBody'
            schemes:
                - http
definitions:
    IssueInput:
        title: IssueInput
        type: object
        properties:
            password:
                type: string
                description: The password of the user
                example: Recusandae illo magnam rerum.
            username:
                type: string
                description: The username of the user
                example: Quis quia mollitia consectetur enim numquam nulla.
        example:
            password: Cumque ut facere.
            username: Et omnis ea.
        required:
            - username
            - password
    RefreshInput:
        title: RefreshInput
        type: object
        properties:
            access_token:
                type: string
                description: The access token of the user
                example: Non rerum laudantium.
            refresh_token:
                type: string
                description: The refresh token of the user
                example: Dolores omnis omnis quo asperiores aliquam.
        example:
            access_token: Placeat illo.
            refresh_token: Reprehenderit et eveniet quasi laboriosam nobis minus.
        required:
            - access_token
            - refresh_token
    TokenDetail:
        title: TokenDetail
        type: object
        properties:
            access_token:
                type: string
                description: The access token of the user
                example: Asperiores rerum possimus.
            expires_in:
                type: integer
                description: The expires in of the user
                example: 8279315110880751817
                format: int64
            refresh_token:
                type: string
                description: The refresh token of the user
                example: Sint quae consequuntur quibusdam.
            token_type:
                type: string
                description: The token type of the user
                example: Numquam aut officiis ea ipsa qui.
        example:
            access_token: Vel libero dolor.
            expires_in: 8657021756071454378
            refresh_token: Consequatur nam atque.
            token_type: Tempore corporis odit aspernatur et dolorum.
    TokenIssueBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Bad Request (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TokenIssueRequestBody:
        title: TokenIssueRequestBody
        type: object
        properties:
            user:
                $ref: '#/definitions/IssueInput'
        example:
            user:
                password: Nobis est sunt consectetur dolore et.
                username: Fugiat quos.
    TokenIssueUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Unauthorized (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TokenRefreshBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Bad Request (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TokenRefreshRequestBody:
        title: TokenRefreshRequestBody
        type: object
        properties:
            token:
                $ref: '#/definitions/RefreshInput'
        example:
            token:
                access_token: Reiciendis blanditiis porro qui unde maiores reprehenderit.
                refresh_token: Qui in molestiae repellat voluptatem.
    TokenRefreshUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Unauthorized (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserCreateBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Bad Request (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserCreateRequestBody:
        title: UserCreateRequestBody
        type: object
        properties:
            user:
                $ref: '#/definitions/UserInput'
        example:
            user:
                name: Dolores fuga asperiores voluptatem aspernatur eum.
                password: Sapiente temporibus vel.
                payload:
                    Dolorem delectus fugit.: Quia illum facere distinctio quam sunt.
                    Et rerum quia odit voluptas repudiandae.: Quo dolores.
    UserDeleteUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Unauthorized (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserInput:
        title: UserInput
        type: object
        properties:
            name:
                type: string
                description: The name of the user
                example: Expedita soluta ex vel et.
            password:
                type: string
                description: The password of the user
                example: Eligendi nihil consequatur.
            payload:
                type: object
                description: The payload of the user
                example:
                    Suscipit non ad adipisci accusamus.: Praesentium dolore.
                    Tempora numquam nisi eaque.: Explicabo ipsum distinctio consequatur consectetur blanditiis repudiandae.
                additionalProperties: true
        example:
            name: Iste voluptatem voluptatibus aspernatur.
            password: Odit in molestiae quos laborum illum.
            payload:
                Doloribus qui est alias consequatur illum ducimus.: Assumenda dolor rerum fugit sed nemo.
        required:
            - name
            - password
